module.exports =
      {unitName : 'testing',
      unitImage : 'https://a0.muscache.com/im/pictures/50616050/43df6979_original.jpg',
      hostId : 3062517,
      hostName : 'testing',
      hostIcon : 'https://robohash.org/exsitautem.jpg?size=50x50&set=set1',
      isSuperhost : false,
      unitAddress : 'testing, United States',
      neighborhood_cleansed : 'testing',
      city : 'testing',
      state : 'WA',
      country_code : 'US',
      property_type : 'Condominium',
      room_type : 'Entire Guest Suite',
      bedrooms : 1,
      beds : 1,
      baths : 1,
      guests : 2,
      unitPrice : '70.00',
      priceModifier : 'per night',
      freeCancellation : 1,
      description_short : 'This lovely, modern room and ensuite bath is detached from the main house, so you can enjoy privacy and quiet. We are a 5 min drive from Ballard and a 15 min drive from downtown. Welcome to our quiet, safe neighborhood!',
      description_long : 'For those who would like more privacy than that offered by a room in someone\'s home, this detached bedroom is a perfect choice!\n\nThe bedroom has a queen bed with a memory foam topper. Power strips on both sides of the bed allow for cell phone charging. Wireless internet and cable tv are provided. There is a small, walk-in closet so that you can unpack and feel at home. The full bath has shampoo, conditioner, and liquid soap, as well as plush towels. The windows bring in plenty of light and fresh air in the summer and there is also an air conditioner, and the floors have radiant-floor heating for the winter months.\n\nI have created a small area to enjoy hot beverages and quick meals. There is a mini-fridge, a hot water kettle, and a French press for your convenience. I provide orange juice, a variety of teas, freshly ground coffee, hot chocolate, instant oat packets, granola bars and fruit. I\'ll also bake scones or muffins on one morning of your stay. With dishes and two chairs, you\'ll be able to have a quick breakfast before you head out for the day.\n\nThere is a hair dryer and umbrella to use as well as beach towels. If you need or forgot something, let me know, and I’ll do my best to accomodate you.\n\nThe guest suite is attached to our garage. The garage will not be in use between the hours of 9pm and 9am. However, during the day, family members will occasionally open the garage door, which can be heard from the guest room.\n\nPlease note that there is not a full kitchen or laundry facilities in your guest suite.\n\nOur guest suite is not kid-friendly. Babies and young children are not a good fit for this listing. Ages 12 and older are welcome, as long as your child is part of the 2 person max. Thanks!',
      amenities : 'Wifi',
      house_rules : 'Not safe or suitable for children (0-12 years)',
      cancellation_policy : 'sure'};

      // `
      // unitName = 'testing',
      // unitImage = 'https://a0.muscache.com/im/pictures/50616050/43df6979_original.jpg',
      // hostId = 3062517,
      // hostName = 'Debbie',
      // hostIcon = 'https://robohash.org/exsitautem.jpg?size=50x50&set=set1',
      // isSuperhost = false,
      // unitAddress = 'Seattle, United States',
      // neighborhood_cleansed = 'Seattle',
      // city = 'Seattle',
      // state = 'WA',
      // country_code = 'US',
      // property_type = 'Condominium',
      // room_type = 'Entire Guest Suite',
      // bedrooms = 1,
      // beds = 1,
      // baths = 1,
      // guests = 2,
      // unitPrice = '70.00',
      // priceModifier = 'per night',
      // freeCancellation = 1,
      // description_short = 'This lovely, modern room and ensuite bath is detached from the main house, so you can enjoy privacy and quiet. We are a 5 min drive from Ballard and a 15 min drive from downtown. Welcome to our quiet, safe neighborhood!',
      // description_long = 'For those who would like more privacy than that offered by a room in someone\'s home, this detached bedroom is a perfect choice!\n\nThe bedroom has a queen bed with a memory foam topper. Power strips on both sides of the bed allow for cell phone charging. Wireless internet and cable tv are provided. There is a small, walk-in closet so that you can unpack and feel at home. The full bath has shampoo, conditioner, and liquid soap, as well as plush towels. The windows bring in plenty of light and fresh air in the summer and there is also an air conditioner, and the floors have radiant-floor heating for the winter months.\n\nI have created a small area to enjoy hot beverages and quick meals. There is a mini-fridge, a hot water kettle, and a French press for your convenience. I provide orange juice, a variety of teas, freshly ground coffee, hot chocolate, instant oat packets, granola bars and fruit. I\'ll also bake scones or muffins on one morning of your stay. With dishes and two chairs, you\'ll be able to have a quick breakfast before you head out for the day.\n\nThere is a hair dryer and umbrella to use as well as beach towels. If you need or forgot something, let me know, and I’ll do my best to accomodate you.\n\nThe guest suite is attached to our garage. The garage will not be in use between the hours of 9pm and 9am. However, during the day, family members will occasionally open the garage door, which can be heard from the guest room.\n\nPlease note that there is not a full kitchen or laundry facilities in your guest suite.\n\nOur guest suite is not kid-friendly. Babies and young children are not a good fit for this listing. Ages 12 and older are welcome, as long as your child is part of the 2 person max. Thanks!',
      // amenities = 'Wifi',
      // house_rules = 'Not safe or suitable for children (0-12 years)',
      // cancellation_policy = 'sure'`